// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAldGmKnqjvfp5p-ZZ9Q2M1BPh_2EqDKHU',
    appId: '1:685685370287:web:6721dad012e94dd3f8135a',
    messagingSenderId: '685685370287',
    projectId: 'life-b2806',
    authDomain: 'life-b2806.firebaseapp.com',
    storageBucket: 'life-b2806.appspot.com',
    measurementId: 'G-NH2YN7JWVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFNHXS2Q47lrFZq_oAHUVNWPnI_lCG6HU',
    appId: '1:685685370287:android:09de6c5ea2277812f8135a',
    messagingSenderId: '685685370287',
    projectId: 'life-b2806',
    storageBucket: 'life-b2806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHr_KtJuPjpfEjMbzLCcrwbQGnRqEbuk',
    appId: '1:685685370287:ios:a1798d99fbf843f1f8135a',
    messagingSenderId: '685685370287',
    projectId: 'life-b2806',
    storageBucket: 'life-b2806.appspot.com',
    iosBundleId: 'com.example.life',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPHr_KtJuPjpfEjMbzLCcrwbQGnRqEbuk',
    appId: '1:685685370287:ios:05bc1fb8c7851f02f8135a',
    messagingSenderId: '685685370287',
    projectId: 'life-b2806',
    storageBucket: 'life-b2806.appspot.com',
    iosBundleId: 'com.example.life.RunnerTests',
  );
}
